<?php

namespace Mesa\ClientesBundle\Entity;

/**
 * ContactosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactosRepository extends \Doctrine\ORM\EntityRepository
{
}
