Mesa\ClientesBundle\Entity\Contactos:
    type: entity
    table: null
    repositoryClass: Mesa\ClientesBundle\Entity\ContactosRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '30'
        apePat:
            type: string
            length: '40'
        correo:
            type: string
            length: '100'
        contrasena:
            type: string
            length: 255
    manyToOne:
        compania:
          targetEntity: Mesa\ClientesBundle\Entity\Compania
          inversedBy: contacto
          joinColumn: 
               name: contacto_id
               referencedColumnName: id
    lifecycleCallbacks: {  }
