Mesa\UsuarioBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: Mesa\UsuarioBundle\Entity\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userName:
            type: string
            length: '20'
        nombre:
           type: string
           length: '50'
        apePat:
            type: string
            length: '50'
        password:
            type: string
            length: '125'
        salt:
            type: string
            length: '125'
        rol:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
